# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/e200_zedboard.xdc

# IP: ip/mmcm/mmcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet
